# Enable recommended Flutter lints
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # === Code style ===
    prefer_single_quotes: true        # Use 'single quotes' instead of "double quotes"
    always_declare_return_types: true # Explicit return types for methods/functions
    sort_constructors_first: true     # Put constructors before other members
    require_trailing_commas: true     # Easier diffs in PRs
    avoid_print: true                 # Use debugPrint / logging instead of print
    prefer_const_constructors: true   # Use const when possible
    prefer_final_fields: true         # Use final for fields that never change
    prefer_final_locals: true         # Use final for local variables
    prefer_const_literals_to_create_immutables: true # Prefer const lists/maps

    # === Documentation ===
    public_member_api_docs: true      # Require docs for all public APIs

    # === Safety & best practices ===
    unawaited_futures: true           # Warn if a Future isn’t awaited
    avoid_dynamic_calls: true
    avoid_redundant_argument_values: true
    unnecessary_late: true
    unnecessary_null_checks: true

analyzer:
  exclude:
    - build/**      # Ignore generated files
    - lib/generated/**
