name: location_navigator
description: "A Flutter package to navigate and find nearby places using location."
version: 1.0.2

homepage: https://github.com/Baralpartha/location_navigator
repository: https://github.com/Baralpartha/location_navigator
issue_tracker: https://github.com/Baralpartha/location_navigator/issues
documentation: https://github.com/Baralpartha/location_navigator#readme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^13.0.1
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
